### ISSUE TITLE
Yarn dev, ReplyError: Ready check failed: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by Vooply** [ornicar/zulip-remind#2]
Hello, I want to use that reminder for zulip, but have some errors
Maybe you can help me with what I do wrong?
![image](https://user-images.githubusercontent.com/43493241/125074388-e62fbf00-e0c5-11eb-92b3-eb815c53082e.png)

**Comment by ornicar** [comment]
did you "download its zuliprc file and put it at the root of this project"?

https://github.com/ornicar/zulip-remind#setup

**Comment by Vooply** [comment]
yep, sure
this file in zulip_remind_master/
and just in case threw in zulip_remind_master/etc/

**Comment by ornicar** [comment]
https://github.com/ornicar/zulip-remind/commit/ab6f6326d7c10c12ec863c97124088d20d98fe63

**Comment by sebastn** [comment]
Was the issue resolved? Why is it closed? I have the same problem.
